### ISSUE TITLE
[maps.usability] Add most common mutations to mutations tab

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#110]
In the mutation tab user should be greeted with a a list of the most common mutations seen in all strains from that country with the frequency listed next to the name. User should be able to click on the mutations they are interested in to see their distribution by drug resistance (as you get from the drop down mutation selection). It would be great to have a short sentence/schematic underneath the drop down that describes what mutation names look like i.e. SNP_2369475_G456T_S315T_katG etc

**Comment by doctormo** [comment]
To do the second part of this, I've put together a small graphic to explain the parts. @mahafarhat can you review the graphic, I think the draft will need editing.

![maps_with_mutation_name_format](https://user-images.githubusercontent.com/589384/31191922-ae544a7c-a90d-11e7-8aaa-67b5449962a8.png)

**Comment by mahafarhat** [comment]
beautiful!

**Comment by mahafarhat** [comment]
the first change in the "nucleotide change" is actually the nucleotide
change, the second is the amino acid position and aa change for
substitutions (SNPs)
coding status = coding and synonymous status
