### ISSUE TITLE
set up pipeline for new strain addition to genTB database

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#113]
In the future as new strain sequencing and phenotype data become available we need to batch process this data and add it to the gentb database (for maps, but also for just sql queries (perhaps from a clone database). This will involve the same pipelines that we are currently applying (megapipe, flatannotator2.0, var2tab, but we may need to adds steps to guard against adding the same strain (with the same ID twice)

**Comment by doctormo** [comment]
I've committed the start of the importing process. The data needed is below in the format taken from the previous databases. Each block of information needs to be accounted for, or labelled as ignored (we don't expect to import it)

## Genes

      "mrna_ntpos" : 0,
      "ntvar" : "A",
      "varcodon" : "",
      "genesymbol" : "",
      "ntpos" : 3337928,
      "snpname" : "SNP_P_3337928_G11A_promoter_ddl",
      "refcodon" : "",
      "ecoli_aapos" : 0,
      "geneid" : "",
      "coding" : "N",
      "aavar" : "",
      "aaref" : "",
      "codonpos" : 0,
      "aapos" : 0,
      "ntref" : "G",
      "syn" : "",
      "snpid" : "3337928GA"

## Mutations

      "snpid" : "7060TA",
      "hqr" : 22,
      "qual" : 200,
      "id" : 99999,
      "aavar" : "I",
      "fq" : 63,
      "depth" : 41,
      "bidir" : "N",
      "hqrref" : 19

## Resistances

      "hivstatus" : null,
      "reth" : "r",
      "patientid" : null,
      "rcys" : null,
      "ramk" : "s",
      "rflpfamily" : null,
      "rgati" : null,
      "rpro" : null,
      "rtha" : "s",
      "rkan" : "r",
      "rmoxi" : null,
      "inttype" : 1,
      "rrfb" : "r",
      "ramoxclav" : null,
      "rrif" : "r",
      "is6110" : null,
      "rcip" : "s",
      "spfamily_parentstrain" : null,
      "rstr" : "r",
      "rlin" : null,
      "name" : null,
      "drtype" : "MDR",
      "roflx" : null,
      "rinh" : "r",
      "id" : 11800,
      "rpas" : "s",
      "rpza" : "s",
      "sptype" : "2",
      "remb" : "r",
      "spoligo_octal" : "000000000003771",
      "rcap" : "s",
      "rclof" : null,
      "rclar" : null,
      "rlevo" : null

## Source

      "city" : null,
      "setting" : "MSLI",
      "patientid" : null,
      "ptsex" : null,
      "clustername" : null,
      "pgg" : 1,
      "ptage" : null,
      "spfamily_parentstrain" : null,
      "rflpfamily" : null,
      "sptype" : null,
      "id" : 1386,
      "hivstatus" : null,
      "country" : null,
      "is6110" : null,
      "name" : null,
      "date" : null,
      "spoligo_octal" : null,
      "otherid" : null,
      "inttype" : null,
      "source" : null

## Targets

      "genesymbol" : "promoter_gid",
      "length" : 131,
      "strand" : "-",
      "stop" : 4408333,
      "start" : 4408203,
      "h37rv_id" : "",
      "type" : "promoter",
      "description" : null

**Comment by mahafarhat** [comment]
Is this resolved?

**Comment by doctormo** [comment]
It is.
