### ISSUE TITLE
map mutations tab stays blank if there are no hits/matches

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#114]
ideally the user gets some obvious feedback that there are no mutation matches, the pop up is a little buggy and fades quickly

**Comment by doctormo** [comment]
Move tooltip for information during search into it's own permanent label.

Making sure that the search results show when correct subsets are entered, example searches:

 * KatG - s315 should show some results
 * RpoB - 526 should show no results
