### ISSUE TITLE
ecoli-TB rpoB coordinate look up

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#115]
for the rpoB gene, a good proportion of scientists use the ecoli coordinate numbering and not our current numbering system, a possible solution is one to 1- add another field to the SNP name that specifies the ecoli number (simpler for the user more complicated on the back end?) or 2- include a look up table for the user so the can find the right coordinate to search for (more complicated for the user)

**Comment by mahafarhat** [comment]
[E18_table.docx](https://github.com/farhat-lab/gentb-site/files/1411172/E18_table.docx)

**Comment by mahafarhat** [comment]
I attached the coordinate matching needed

**Comment by doctormo** [comment]
Use the old_id to store the old ecoli numbers and add the old_id to the search field for the mutations lookup.

**Comment by doctormo** [comment]
Addendum: We already have a field 'ecoli_aapos' which should contain the amino acid position information, should this field now be a new sister-field which would contain the codon position for the same thing?

**Comment by mahafarhat** [comment]
Yes you can use this field, but I believe it's most empty right now. You can populate it with the data in teh E18_table previously attached on Oct 24th.

**Comment by doctormo** [comment]
Codons are the AApos, label when doing an ecoli lookup should add (E: V13F) to the end and a prefix should be used when doing the lookup with an aditional description to describe how to do the lookup.
