### ISSUE TITLE
Explore page not working

### ISSUE THREAD

**Issue by SBassler** [farhat-lab/gentb-site#124]
![image](https://user-images.githubusercontent.com/38661384/42112983-bc75edc2-7bb7-11e8-87fe-651713e6c744.png)

**Comment by mahafarhat** [comment]
A job for our interns

**Comment by mahafarhat** [comment]
Martin we need to pull and deploy the new TwoRavens repository available here:
https://github.com/TwoRavens/TwoRavens

**Comment by raprasad** [comment]
@mahafarhat @doctormo 

- Last year Dataverse switched to a different exploration tool and they no longer maintain the TwoRavens page embedded in https://gentb.hms.harvard.edu/explore/ 
- You should be able to switch the embedded page to a link given by the “Explore” button on a particular data file.  For example:
   - Go to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/FQACLW
   - Use the page link that pops up when clicking "Explore"
   - See attached screenshot

![Replication_Data_for__Input_Mycobacterium_tuberculosis_data_for_Resistance_Deep_Learning_Model_-_Tuberculosis_Dataverse](https://user-images.githubusercontent.com/1036060/58736339-72da0000-83cb-11e9-982a-869090a37adf.png)

**Comment by mahafarhat** [comment]
Unfortunately the explore functionality provided by dataverse only provides an excel view of the data which I don't think is very useful. 
Tasks: 

1) let's decommission explore, and all references to it on the website.
