### ISSUE TITLE
extension problem with dropbox upload

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#127]
As of posting this, the problem is still resolved

**Comment by doctormo** [comment]
That's good isn't it? resolved?

**Comment by mahafarhat** [comment]
ok files are no longer grey, I am able to select them but then I get the following error and no uploaded is started:
![screenshot_2018-08-06 create fastq pair-ended prediction - gentb](https://user-images.githubusercontent.com/8130645/43729302-d61297a4-9975-11e8-9466-c6065fb48e1e.png)

**Comment by mahafarhat** [comment]
I think this is resolved now
