### ISSUE TITLE
predict manual upload broken

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#138]
The dropdown boxes to select genes and mutations within predict manual are not working, no suggestions give and user cannot select a mutation.

**Comment by mahafarhat** [comment]
this piece is still broken, there is no longer a drop down to select genes and mutations in the current live version.

**Comment by doctormo** [comment]
Maha, I've fixed the error that caused the crash, but the database is missing all information about how drugs related to mutations. Each drug has an empty mutations list, this is true of both the live site and my own copy on my computer.

**Comment by mahafarhat** [comment]
Hi Martin, bizarre, must have been deleted by error. There must still be
some information relating drugs to mutations as the predict output
exploration still displays mutation for each drug when you click on the
probability square.

Maha
