### ISSUE TITLE
lineage calling is not done in the improved megapipe

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#140]
we need to implement lineage calling

**Comment by Davey-Hughes** [comment]
Ah. I temporarily skipped that because it wasn't necessary for predict. It shouldn't be too bad to add it.

**Comment by mahafarhat** [comment]
talk to @ejfresch he has a new fast version, I think its best not to implement the spoligotype lineage caller (the C++ code that works off fastq), as we're learning its less accurate.

**Comment by ejfresch** [comment]
The repo is here: https://github.com/farhat-lab/fast-lineage-caller-vcf

**Comment by mahafarhat** [comment]
This is now resolved
