### ISSUE TITLE
email notification to developer and user on job status

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#152]
At the conclusion of each job, we need the webhost to send an email to the user and to Maha on if the job succeeded or failed with a link to the results. We need to include a disclaimer that the gentb is still in beta-format and runs on an academic compute cluster. Disclaimer that compute outages or delays in job batching are an ongoing challenge that we are working to resolve.

**Comment by mahafarhat** [comment]
Any update on this from O2 support?

**Comment by doctormo** [comment]
Not a sausage.

**Comment by mahafarhat** [comment]
@doctormo I've been getting emails, so I will close this for now. let me know if this is still an issue.
