### ISSUE TITLE
mutation display need to be refined - Predict

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#156]
There was a bug in generate matrix that was resulting in missed promoter mutations. After fixing this the mutation display is no longer very clear. Also the genes need to sub-selected by drug for clarity - do we still have a correspondence table between genes and drugs ?

Attaching a screenshot here:
![image](https://user-images.githubusercontent.com/8130645/59034325-d08da280-8838-11e9-9162-beaf7ec67743.png)

**Comment by mahafarhat** [comment]
In the screen shot you can see the mutation L13F in oxyR gene, has a genetic region label of 'L13F-oxyR' instead of oxyR

**Comment by mahafarhat** [comment]
@doctormo I'll extend this issue to cover the points we just discussed

Specifically we need the x axis on the mutation plot to be more restricted as otherwise the locus labels are impossible to read. We should have the following regions regardless by drug, and then any other mutations that are passed on in the json file:

drugs_to_genes = {
                'AMK':set(['rrs']),
                'CAP':set(['rrs','tlyA']),
                'CIP':set(['gyrA','gyrB']),
                'EMB':set(['embB','embC','embA','Rv3806c','promoter-embA-embB']),
                'ETH':set(['ethA','promoter-fabG1-inhA','inhA']),
                'INH':set(['katG','promoter-fabG1-inhA','inhA','kasA','promoter-ahpC','promoter-embA-embB']),
                'KAN':set(['rrs','rrl','eis','inter-eis-Rv2417c']),
                'LEVO':set(['gyrA','gyrB']),
                'OFLX':set(['gyrA','gyrB']),
                'PAS':set(['thyA','inter-thyX-hsdS.1','folC']),
                'PZA':set(['pncA','promoter-pncA','rpsA']),
                'RIF':set(['rpoB']),
                'STR':set(['rpsL','gid','rrs','inter-rrs-rrl'])
        }

**Comment by doctormo** [comment]
This is now fixed. All data entered into a new database manytomany relationship which records the which loci are important to drugs and the matrix plot is restricted to just those plus the ones shown in that drug on the plot.

**Comment by mahafarhat** [comment]
I'm reopening this issue as for the drug ETH no genes seem to be recognized. e.g from clicking on the ETH square for this strain
![image](https://user-images.githubusercontent.com/8130645/60351342-93c64e80-9993-11e9-9ecf-c9ecc47092a3.png)

**Comment by doctormo** [comment]
Fixed!
