### ISSUE TITLE
investigate a failed display of results

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#159]
@doctormo can you please investigate why this job:
https://gentb.hms.harvard.edu/predict/a944ea401416a070a1f6431858efe0a8/

failed to display any results.

Note it may be because I pushed new changes to the enhancer code, and the json file is slightly different?

**Comment by doctormo** [comment]
Fixed and pushed live. It was barfing trying to parse one of the mutation names. I've asked the code to skip mutations it can't parse.
