### ISSUE TITLE
Mutation list not changed by Gene Locus Selection

### ISSUE THREAD

**Issue by doctormo** [farhat-lab/gentb-site#165]
In the maps feature, the mutations list isn't changed by any of the selected data points from the left side. i.e. input source, country, drug, locus etc. The first three, country, drug, input source should change the strains selected, while the loci selections should change the mutations directly.

The way the mutations list should be filtered by the strains is that they should only appear if there is information about resistance about that mutation available. At the moment is very naieve and is showing all mutations no matter what. this can be seen currently in how selecting mutations yields an empty graph (because all the mutations selected don't have any data to show).

So this issue is two stage. Make sure loci selections are filtering directly, then make sure all the other strain filters are effecting the mutations list.

I believe the graph portion is already being filtered, but it should be double checked to make sure that this data is also filtered by strain correctly (filter by locus is unnecessary)

**Comment by mahafarhat** [comment]
I want to add that I don't think the bar plot graph portion is filtering accurately either. Here is an example where all 100% 26 sensitive strains seem to have a resistance mutation (this is not possible)

![image](https://user-images.githubusercontent.com/8130645/60597679-568a0400-9d79-11e9-924d-46abfc433ace.png)

**Comment by mahafarhat** [comment]
can we prioritize this issue @phanaj @doctormo

**Comment by mahafarhat** [comment]
I can see the list is limited by gene. However at the moment the list of mutations generated (in the mutations tab) contains mutations that are not present in that data subset. these needs to be corrected. I'll make a separate issue for this task.
