### ISSUE TITLE
fast lineage caller in MP2

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#167]
did we make any updates to fast lineage caller?
Previously this strain was called 'mixed' and now it says its "unknown lineage format" and crashes the processing. Let's go back to what it was doing before. 
![image](https://user-images.githubusercontent.com/8130645/60835742-e83aac80-a191-11e9-86b5-69acc61a6e19.png)

**Comment by mahafarhat** [comment]
also here @doctormo even though all other strains ran successfully no results are displayed at all.

**Comment by doctormo** [comment]
We'd have to look at the file. But the gentb website is currently down. I've sent a ticket.
