### ISSUE TITLE
MAPs: Mutation tab mutations error

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#168]
old title still applies to issue discovered today. Mutation tab does not load data after gene selection.
we get the following error: 

`DataTables warning: table id=DataTables_Table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

<img width="1192" alt="Screen Shot 2021-02-25 at 4 58 39 PM" src="https://user-images.githubusercontent.com/8130645/110035036-25f62c80-7d09-11eb-9461-41ec19e8c4b8.png">

**Comment by doctormo** [comment]
Can you explain which selections should effect the mutations? I presume the Data Source could restrict it, but how would country or drug?

**Comment by mahafarhat** [comment]
we still get lines of mutations that are empty, (ie. get zero counts in the bar graph if you click on them). these should not appear in the list, ie it should not be possible to select them to begin with
