### ISSUE TITLE
Upload data into MAPs

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#169]
@doctormo top priority item is now to enrich a large number of vcfs and upload for testing the MAP functionality. Can we please prioritize this

**Comment by mahafarhat** [comment]
Tasks:
1) identify input metadata and vcfs
2) develop an algorithm to package metadata for each isolate
3) clean/QC metadata
4) enrich VCF

**Comment by doctormo** [comment]
This task is completed.
