### ISSUE TITLE
MAPs: when drug is selected, mutation should be tabulated accross that drug phenotype in mutations tab

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#170]

**Comment by mahafarhat** [comment]
at the moment the mutation is tabulated accross the following categories: "sensitive", "other resistant", "MDR", "XDR"
When a drug is selected the mutations display should tabulate against "drug=resistant" and "drug=sensitive" and "drug=unknown"

**Comment by doctormo** [comment]
Closed wrong issue, this issue isn't fixed yet. I'm not sure yet what the task is, is it to rename the labels in the table or is it to do something else?

**Comment by mahafarhat** [comment]
no it's not a renaming issue
the point of selecting a drug in the drug tab  e.g. INH is to tabulate the frequency of mutations in isolates resistant to that drug vs susceptible to the drug. At the moment we get a generic tabulation of mutation frequencies by general categories of resistance as listed above.

**Comment by mahafarhat** [comment]
I don't think the drug selection is otherwise used anywhere 

(unless you currently use it to exclude isolates with out a phenotype result for that drug??)

**Comment by doctormo** [comment]
So there should be some extra columns in the table detailing how many sensitive vs. resistant etc strains?

**Comment by mahafarhat** [comment]
yes the same column you use to display the resistant vs sensitive for each drug in teh drug tab.

**Comment by mahafarhat** [comment]
@doctormo note tested this again this am, and although mutations tab is very very slow it did eventually load and the bar plot still display number of strain categories but the broad resistance categories and not the drug I selected

![image](https://user-images.githubusercontent.com/8130645/63433740-cc156680-c3f1-11e9-8e76-0c85f47d16b9.png)

Also list of mutations still contains empty ones:
![image](https://user-images.githubusercontent.com/8130645/63433812-e4858100-c3f1-11e9-83d3-8436180285e7.png)
