### ISSUE TITLE
Fix the absolute paths on the vcf to csv program step of wdnn-from-vcf pipeline

### ISSUE THREAD

**Issue by cbintz** [farhat-lab/gentb-site#204]

**Comment by mahafarhat** [comment]
@mgro we discussed you will try to reference the pickle files internally in this python script. Hopefully this will fix the permissions issue we are experiencing with the WDNN pipeline. If not please close this issue and start a new one assigned to Martin.

**Comment by mgro** [comment]
@mahafarhat or @doctormo this can be closed
