### ISSUE TITLE
Revise lipworth scheme from predict lineage caller

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#207]
Lipworth snp scheme has errors and currently producing incorrect predictions. Luca can fix this error later (low priority), but he stated that by deleting the lipworth snp data file we can stop generating a prediction automatically using this scheme. Lipworth prediction should be deleted from the site.

**Comment by mahafarhat** [comment]
Ok I did discuss this with @ejfresch. @ejfresch said we should report the snp counts for lipworth scheme as percentages next to the lineage call itself. it is better to keep the lipworth scheme as it is the only one that has animal lineages and gives families ~ to spoligotyping.

**Comment by mahafarhat** [comment]
@ejfresch @doctormo can you please work together to resolve this issue by 4/20?

**Comment by doctormo** [comment]
The Lineage webpage is controlled by the pipeline, whatever appears in that resulting lineage file is what is displayed to the user, no filtering is applied except to shuffle each into the right columns.

@ejfresch Do you know what parts of the lineage caller pipeline program need to be modified to do what Maha wants here?
