### ISSUE TITLE
Setting aligner minimap2 to short-read mode with prior paired fastq check

### ISSUE THREAD

**Issue by mgro** [farhat-lab/gentb-site#217]
Minimap2 is currently not run in short-read mode. Current command is `minimap2 -a`, short-read mode that takes paired read information into account `minimap2 -ax sr`.

Before changing this it would be necessary to ensure paired fastq files are in the same order and are exact matches (i.e., each read identifier in the first fastq file has its exact matched pair in the second fastq file). 

There is a [script](https://github.com/BioInfoTools/BBMap/blob/master/sh/repair.sh) from [BBMap](https://github.com/BioInfoTools/BBMap) that does exactly this. It can be called as follows:

 `repair.sh in1=fastq1.fq in2=fastq2 out1=fixed1.fq out2=fixed2.fq outs=singletons.fq repair`

**Comment by mahafarhat** [comment]
ok we discussed this and we just need to change minimap2 -ax sr and do some testing. @mgro please close this issue when its complete.

**Comment by mahafarhat** [comment]
OK this is now implemented.
