### ISSUE TITLE
MAPs: testing of new 12k benchmarking data

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#227]
New large data has been uploaded and we have to test that MAPs behaves as expected. 

Several issues have come up so far:

1- Clicking world generates no maps
2- Previously after clicking country we were generating no gene lists.

As we fix the above issues, let's retest and add any new issues here to resolve.

**Comment by mahafarhat** [comment]
Ok above has been resolved. Also numbers are very similar to what you expect, do you agree @mgro ?

**Comment by mgro** [comment]
I agree - this can be closed.
