### ISSUE TITLE
Add additional text to guide user during file upload and output exploration

### ISSUE THREAD

**Issue by mgro** [farhat-lab/gentb-site#230]
- Add 'Single-end FastQ File' and 'Paired-end FastQ File' as bold headers on the upload page next to the logos
- Add 'Click on the heatmap to explore drug resistance mutations' or something similar below or above the Resistance prediction heatmap

**Comment by mgro** [comment]
- we could also link to the [Snakemake repo](https://github.com/farhat-lab/gentb-snakemake) at the Bottom of the `Predict` page

**Comment by mgro** [comment]
- maybe explain abbreviations (FPR/FNR) in the prediction / output tab

**Comment by mgro** [comment]
![Screen Shot 2021-03-24 at 7 26 20 PM](https://user-images.githubusercontent.com/22810016/118342334-e14cf580-b4f0-11eb-9104-b0c7df2dee35.png)
![Screen Shot 2021-03-24 at 7 28 18 PM](https://user-images.githubusercontent.com/22810016/118342335-e1e58c00-b4f0-11eb-91e0-76c339ecceb7.png)

**Comment by mahafarhat** [comment]
Actually this is beyond my very limited html. @doctormo to the rescue

**Comment by doctormo** [comment]
I've fixed the first two, but the snakemake item is undefined. What is the predict page in this context?

The screenshots really helped here, I would have had no idea without them. Thanks!
