### ISSUE TITLE
An option to retire a pipeline

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#234]
We need an option to retire a pipeline: i.e. such that it's kept in the admin interface but is not displayed to the user as an option for a particular data input.

**Comment by doctormo** [comment]
Completed and deployed live.

**Comment by doctormo** [comment]
![Screenshot from 2021-04-15 13-33-00](https://user-images.githubusercontent.com/589384/114913407-26e1aa00-9def-11eb-93eb-f23263fd1c8d.png)
