### ISSUE TITLE
link to user friendliness survey on predict output page

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#238]
Let's add @mgro 's survey on predict result page for each dataset.
This is the[ link ](https://docs.google.com/forms/d/e/1FAIpQLSflFOSOSSXhElFewA2Fm55_XS_sC3dM14ok6UewsI0fHaU7SQ/viewform)to the google survey. Martin please add some text to guide the user e.g. 

"Please give us feedback on GenTB predict here. "

**Comment by mgro** [comment]
Note to self @mgro - update instruction's on survey

**Comment by doctormo** [comment]
![Screenshot from 2021-05-16 13-10-07](https://user-images.githubusercontent.com/589384/118405939-1586fa00-b648-11eb-8602-9c2bd31f4c30.png)
