### ISSUE TITLE
After user submits a predict job they should be notified than an email will be sent to them when the results are read

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#239]
The user should get feedback during upload direct from computer (as this is slow) and after data is uploaded on the 'processing' page.

**Comment by doctormo** [comment]
![Screenshot from 2021-05-16 13-12-55](https://user-images.githubusercontent.com/589384/118405998-74e50a00-b648-11eb-94db-63187c6a9f3f.png)
