### ISSUE TITLE
Emails to user contain contradicting information

### ISSUE THREAD

**Issue by mgro** [farhat-lab/gentb-site#241]
I received an email (see below) with *Status*: Prediction Ready and below 'Sorry! The Processing has failed'.

WARNING: Harvard cannot validate this message was sent from an authorized system. Please be careful when opening attachments, clicking links, or following instructions. For more information, visit the HUIT IT Portal and search for SPF.

- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
-----------
Dataset
-----------

* Title: test_04_combinedV2
* Description: test_04_combinedV2
* Status: Prediction Ready

Sorry! The processing of your file has failed.

We are sorry for any inconvenience, we are looking into the error and will email you about next steps shortly.

Link to your dataset details page: https://gentb.hms.harvard.edu/predict/d9d234f20b91a5a7e4bc0f86680c5569/

-----------
Processing
-----------

* Peru4912: [==================] Prediction Ready

-----------
Contact
-----------
* Name: mgroeschel
* Affiliation: Harvard Medical School
* Email: matthias_groeschel@hms.harvard.edu

(May 15th, 2021 10:37:19 p.m.)

**Comment by mahafarhat** [comment]
This is a consistent error that I think affects all user emails.
