### ISSUE TITLE
new bug in mutation display from heatmap

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#242]
We seem to have a wrong drug to mutations mapping: we are supposed to only see rpoB, and rpoB promoter for RIF, instead we see some INH resistance genes:

**Comment by mahafarhat** [comment]
https://gentb.hms.harvard.edu/predict/a49acfd4b84f3871079a68687766e56a/

and click on RIF

**Comment by mahafarhat** [comment]
The bug may be bigger than I thought, I see resistance being predicted for STR and PZA but no mutations are showing up for the respective genes on the display. I checked the json files and the correct mutations are there.

**Comment by doctormo** [comment]
This issue is with the parsing of the data, it gets stored as PredictResultLocus objects which by that point as wrong.

**Comment by doctormo** [comment]
Sorry for the delay Maha, I got stuck on this issue. I believe I'ved fixed the issue and cleared out the old result save.
