### ISSUE TITLE
Mutation table on GenTB - Map shows the same letter in two columns 

### ISSUE THREAD

**Issue by mgro** [farhat-lab/gentb-site#248]
The `aaref` and `aavar` columns are showing the same amino acid letters. See highlighted in screenshot

![Screen Shot 2021-06-10 at 11 27 22 AM](https://user-images.githubusercontent.com/22810016/121553717-83bca380-c9df-11eb-8d6f-9e6fe849a3ea.png)

**Comment by doctormo** [comment]
Of *780,936* mutations in the database, *12,490* has the same `aaref` and `aavar` of these, 9,848 could be fixed by setting the `aaref` correctly from it's stored reference codon. The remaining 2601 are synonymous and 41 of them were INDEL types with the same nucleotides.

There was no known location for import errors, this is likely input data gone wrong.

Can you confirm the data is now fixed on live?

**Comment by mgro** [comment]
Yes, I can confirm this is fixed. Thank you!

From: Martin Owens ***@***.***>
Date: Monday, 4. October 2021 at 18:27
To: farhat-lab/gentb-site ***@***.***>
Cc: Groeschel, Matthias ***@***.***>, Author ***@***.***>
Subject: Re: [farhat-lab/gentb-site] Mutation table on GenTB - Map shows the same letter in two columns (#248)

Of 780,936 mutations in the database, 12,490 has the same aaref and aavar of these, 9,848 could be fixed by setting the aaref correctly from it's stored reference codon. The remaining 2601 are synonymous and 41 of them were INDEL types with the same nucleotides.

There was no known location for import errors, this is likely input data gone wrong.

Can you confirm the data is now fixed on live?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_farhat-2Dlab_gentb-2Dsite_issues_248-23issuecomment-2D933649545&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=0psJbq2Flm1s3w-x37dkDVxnTGAjIIVix4qI8iUUK5s&s=224tSY2sa5sFqbWT8QDu4MlFCGNv8TQ_gocrTy62-1s&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFOA3IBD73DX67JQQND444TUFHIWRANCNFSM46OYUJ6Q&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=0psJbq2Flm1s3w-x37dkDVxnTGAjIIVix4qI8iUUK5s&s=SOQvypFsnElS2jtBCD_fICqZDUChnFsiszX4X8zYBbQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=0psJbq2Flm1s3w-x37dkDVxnTGAjIIVix4qI8iUUK5s&s=DgGol_XD6B9w6plcwDqcdzvzD5AaHSuIhTJLMzpErYo&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=0psJbq2Flm1s3w-x37dkDVxnTGAjIIVix4qI8iUUK5s&s=K3DMAzt-w6hJwR61eDuSB4EYTFOJRkG4-wRv0f102yo&e=>.
