### ISSUE TITLE
WDNN predict result display

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#253]
WDNN output, displays only 5 drugs instead of 13, although json file has drug prediction for 11 drugs. Note drugs predicted by the usual pipeline were 13, but the set of 11 is contained in the set of 13. 

here is an example:
prediction:
https://gentb.hms.harvard.edu/predict/ee5c533e80721e0c3f97762fd139719d/

json:
https://gentb.hms.harvard.edu/tb/media/data/tbdata_00000786/Peru4912_cut.matrix.json

**Comment by mgro** [comment]
The same happens with the Paired-end 2.2. pipeline. 

Here the heatmap is not displayed correctly: https://gentb.hms.harvard.edu/predict/a39ad87c9ed3e4a215dae07bd9d2f0d7/

But interestingly here it is (same pipeline run): 
https://gentb.hms.harvard.edu/predict/629c20fa6465605ed3cf7bb89277991a/

**Comment by doctormo** [comment]
This is now fixed and live.
