### ISSUE TITLE
Antibiogram app

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#254]
We want to create a modified version of the Maps, that only has 'country' and 'drug' side tabs. This new 'antibiogram' app, will be  displayed alongside Maps, Predict, and Data on the main website and on the upper bar.

The input is Avika's antibiogram dataset. We are aiming for a display that has the features of the following Tableau map:
https://public.tableau.com/views/MarginalResistance/Sheet1?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link (one example)

There are three types of antibiograms we want to display (this will be an initial fork with three options: margin, rifampicin susceptible and rifampicin resistant. 
https://public.tableau.com/app/profile/avika8515

We have the option of embedding this new feature as a Tableau frame:
https://help.tableau.com/current/pro/desktop/en-us/embed.htm

**Comment by doctormo** [comment]
First draft of this antibiograms feature is now live:

https://gentb.hms.harvard.edu/maps/antibiogram/

This includes:

 * A new maptables app which is able to import many custom map tables using an import command line script and links countries and drugs to the given data, this includes new database tables for holding the data.
 * A new set of views for the antibiograms views, including map page, menus and needed infrastructure
 * Fixes to the existing vertical tabs to allow it to handle more than one vertical tab interface.
 * New country map entries to cope with a few country names not previously known
 * Cleaned up mutations maps, urls, filenames to make them distinct from antibiograms maps

**Comment by mahafarhat** [comment]
Some features to refine/add:

- Default drug seems to be PAS right now, can we change it to INH among Rif susceptible (mean_snp10_res_rs)
-The “Lower” and “Upper” estimates for resistance are flipped
- Instead of seeing a separate “Drug” tab, can we have a drop down menu near the map to select the drug of interest?
- user needs to filter by 'Drug', a separate filter by 'estimate type' (marginal, resistance among rif susceptible, resistance among rif resistant), and a third filter by 'lower limit on sample size' (50, 100) 

**A reminder of which variable we need for each 'estimate type' 

1. marginal resistance rate (p_a_r variable from my data file) 
2. mono-resistance (mean_snp10_res_rs) and 
3. resistance-among RR (mean_snp10_res_rr)

**Comment by doctormo** [comment]
* I don't know what `among Rif susceptible (mean_snp10_res_rs)` means, there's no mean_snp10_res_rs column and Rif is a different drug isn't it.
 * Fixed
 * Please confirm you want this engineered. It will take extra time.
 * This is three filters, I'm not sure at all what the filtering is supposed to do. Remove them from the map? Show only them on the map? Field `mean_snp10_res_rs` doesn't exist, should it be `mean_snp10_rs`? Same for `mean_snp10_res_rr` which also doesn't exist.

**Comment by doctormo** [comment]
I've fixed what I can for today, I'm improved the apps flexibility so it'll be much easier to change some of the items above no matter what happens, and should allow us to show more types of data in the maps.

I'll add the filtering next week if the details can be provided. Mostly I just need to know the mechanism expected.

**Comment by avdixit** [comment]
Yes the correct columns are: 

mono-resistance (mean_snp10_rs)
resistance-among RR (mean_snp10_rr)

**Comment by avdixit** [comment]
Filtering:

- User should be able to filter by drug, i.e. see only the selected drug on the map 
- User should be able to filter by “lower limit on sample size”, I.e. see only countries where “gentb_snp10_n” is used to show countries only if the n >= 50 or n >= 100
- “Estimate type” - user should be able to see only one of the three filters Maha mentioned above

**Comment by mahafarhat** [comment]
A reminder that these tableau maps are what we need, you can use these as examples of the filtering:
We are aiming for a display that has the features of the following Tableau map:
https://public.tableau.com/views/MarginalResistance/Sheet1?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link (one example)

There are three types of antibiograms we want to display (this will be an initial fork with three options: margin, rifampicin susceptible and rifampicin resistant.
https://public.tableau.com/app/profile/avika8515

**Comment by mahafarhat** [comment]
the three maps should represent the filtering by estimate type, as noted above in the thread

**Comment by doctormo** [comment]
Note to future: the filtering mechanisms are evident in the example tablue in the first posting.

**Comment by mahafarhat** [comment]
Regarding "Instead of seeing a separate “Drug” tab, can we have a drop down menu near the map to select the drug of interest?"
Please engineer this if it will take < 5 hours of work.

**Comment by doctormo** [comment]
Today the drug filtering was moved into the main body and a start was made on getting the other filtering to work. Although this is proving to be a bit more involved it's progressing nicely.

![Screenshot from 2021-09-06 16-53-26](https://user-images.githubusercontent.com/589384/132260028-8ff0d92e-fd0d-4426-bc4b-04a936cca719.png)

**Comment by doctormo** [comment]
Question for next week: when you say "Estimate type" what you mean is "These are the different columns which the data should be based on"? which isn't a filter, it's a selector (or data source). Please confirm as filtering on these columns can be possible, but if the map always shows the same column in the map colours you may get grumpy.

If it's true that these are different map column sources. Wouldn't it be better to have them as three different maps on the side (where you currently see "World") instead of trying to make them fit in as a fancy filter?

**Comment by avdixit** [comment]
Thanks Martin - i see what you mean. I think it would better to have them as a filter rather than three different maps. I could’ve just made the table in a more “long” format then it would have been a filter. Maha may also have additional thoughts.

**Comment by avdixit** [comment]
On further thought, three different Maps does sound like a simpler solution but I would defer to Maha on this. A few additional comments: 

- We don't need to have the "Drug" tab that is showing up right now. 
- We need another level of filter (higher than the "estimate type" filter) to separate the data from WITHOUT outbreak correction and WITH outbreak correction (the latter are variables with "snp10" in the variable name in the attached file). 
[Supp Table 3 WHO Corrected Marginal Estimates.xlsx](https://github.com/farhat-lab/gentb-site/files/7122907/Supp.Table.3.WHO.Corrected.Marginal.Estimates.xlsx)

- The "Lower" and "Upper" estimates are still flipped. 
- "PZA" is still the default drug, let us make it INH
- The estimates for drugs that I can see right now for the Marginal Resistance Map do not match the maps on tableau. Need to make sure these are being calculated correctly: [Marginal Resistance Rate before outbreak correction = p_a_r*100; Lower Marginal Resistance Rate before outbreak correction = (p_a_r-(1.96*sqrt(var_a_r)))*100; Upper Marginal Resistance Rate before outbreak correction = (p_a_r+(1.96*sqrt(var_a_r)))*100; Marginal Resistance Rate after outbreak correction = p_a_r_snp10*100, Lower Marginal Resistance Rate after outbreak correction = (p_a_r_snp10-(1.96*sqrt(var_a_r_snp_10)))*100, Upper Marginal Resistance Rate after outbreak correction = (p_a_r_snp10+(1.96*sqrt(var_a_r_snp_10)))*100]

**Comment by doctormo** [comment]
Hi Avika, some of the items above are because the fixes are not deployed yet. Please bare with me while I get the map situation sorted out.

@mahafarhat Are multiple maps ok?

**Comment by avdixit** [comment]
Thanks Martin! I can confirm on behalf of @mahafarhat that multiple maps as you suggested are good to go, we discussed this on Friday.

**Comment by doctormo** [comment]
@avdixit I've put together the software and deployed it to o2 and have created three maps based on the above instructions ( we can tweak these further)

You can see the maps here: https://gentb.hms.harvard.edu/maps/antibiogram/

I'll do some more testing to see how it goes on live.  But for now I'm attaching an animated gif of how you can create and edit the map information as needed:

![adding-a-new-map](https://user-images.githubusercontent.com/589384/133128076-cf34c894-d4f8-41d8-a89d-9c8d6aca4a54.gif)

**Comment by mahafarhat** [comment]
@doctormo one last feature, and one minor fix to add and we can close this issue. 
1- 
I noticed the map color scale does not adapt to the data range for each map, e.g.
click mono-resistance > drug=LEVO > Limit by sample size = 50
and you get this all white map
![image](https://user-images.githubusercontent.com/8130645/134553444-4a07051c-1c93-4b05-b012-3fccf25369da.png)

I do care a lot about the difference between 0.5% and 2.5% in that plot, can we scale the color palate so it only spans the range of available variable values based on the filtering?

2- please delete marginal resistance from the title of the map

**Comment by doctormo** [comment]
This should now be fixed.

![Screenshot from 2021-09-27 13-44-20](https://user-images.githubusercontent.com/589384/134958875-18c24d7b-d978-4d8d-81eb-01743a9efefa.png)
