### ISSUE TITLE
Display probability instead of binary resistance value when hovering over drug heatmap

### ISSUE THREAD

**Issue by mgro** [farhat-lab/gentb-site#255]
It would be great if instead of the binary resistance value (1 or 0, according to which the heatmap is colored) we would see the probability value (the last item in the list of drug-lists in the JSON). 

So the heatmap is colored according to binary resistance 1 or 0, but shown is the probability. 

<img width="412" alt="Screen Shot 2021-08-24 at 11 34 45 AM" src="https://user-images.githubusercontent.com/22810016/130593806-c7aef01e-a2ac-465d-b7a4-1a0086413342.png">

**Comment by mgro** [comment]
See here the 'old' format currently in use by the default pipeline, that is *not* featuring the binary resistance number:
[pipeline_2.1._old_format.txt](https://github.com/farhat-lab/gentb-site/files/7079030/pipeline_2.1._old_format.txt)

This will be the new default, featuring an additional item in the drug-lists (binary resistance *and* probability of resistance):
[pipeline_2.2_new_format.txt](https://github.com/farhat-lab/gentb-site/files/7079029/pipeline_2.2_new_format.txt)

**Comment by doctormo** [comment]
This is now done, where there is a prediction format.
