### ISSUE TITLE
Mutations app glitches and improvements

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#256]
Request the following edits to the Maps > Mutations app

1- Instructions for the gene selection tab: Please change 'locuses' to 'loci'
2- When a gene locus is selected, e.g. katG, the gene locus tab does not indicate the gene locus name
3- When you unclick or double click a mutation, the left sided tab bar disappears:
4- When a mutation and drug is clicked the mutation table gives the count of mutations in resistant isolates, we phased out the bar plot we previously had below the table that showed the break down of mutations count among resistant and susceptible. Can we restore this feature?
5- In the Maps the data display when clicking over a country is too large, it makes navigation quite 'clunky'. Instead of having the user color by the different variables listed at the top of the maps, can they click what data to display in the box and keep the coloring by total isolates as we had previously?

Data display while hovering over country is too large:

![image](https://user-images.githubusercontent.com/8130645/131945310-33ded925-a4ed-40b8-80ae-fd4f1fe4ecd7.png)

Gene locus name is NOT displayed in the tab after selection:

![image](https://user-images.githubusercontent.com/8130645/131945913-f1965de5-c5b8-42ac-bc6e-c97d173a892c.png)

When you unclick or double click a mutation, the left-sided tab bar disappears:

![image](https://user-images.githubusercontent.com/8130645/131946074-b356705c-6050-4cd8-860f-55c2e8d7710f.png)

**Comment by doctormo** [comment]
All items except number 5. is fixed. I think 5 is a full blown feature request and should have it's own issue with a design in mind about what it will look like. If possible.
