### ISSUE TITLE
Data display while hovering over country is too large (Maps>Mutations)

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#257]
Issue simplified from the previous number '5'

In the Maps the data display when clicking over a country is too large, it makes navigation quite 'clunky'. When the user clicks on color by variable up top, we should display Total sample size, MDR sample size, and the selected variable only (none of the others), keep color by variable feature as is. 

Data display while hovering overcountry is too large:

**Comment by doctormo** [comment]
Not all countries have data, this makes it optional, but may not display the column if no data is available.

![Screenshot from 2021-09-27 11-50-36](https://user-images.githubusercontent.com/589384/134942286-04f96756-cafe-4481-bd90-04b7f7dfbd3b.png)
