### ISSUE TITLE
Add R/S label to hover box over drug/strain for Predict

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#258]
We have successfully displayed R/S prediction as Red/Blue in binary form in predict. But currently, the hover box only lists the probability but not the prediction:

![image](https://user-images.githubusercontent.com/8130645/134921149-7369f3d3-e251-4bbb-a2ad-02ece6b25b68.png)

Let's add a line under 'drug' that states
**Prediction** Resistant 
or
**Prediction** Susceptible

**Comment by doctormo** [comment]
![Screenshot from 2021-09-27 10-41-39](https://user-images.githubusercontent.com/589384/134930945-ca4505a3-2ae4-486c-a548-3292a22e00a9.png)

Feature added, deployment expected later today.

**Comment by doctormo** [comment]
Related to this I've fixed an annoying issue with empty squares having a bad hover, it'll now tell you the drug and a "No data" message. This will happen infrequently, but it's worth clearing up
![Screenshot from 2021-09-27 10-58-40](https://user-images.githubusercontent.com/589384/134933935-1ec3d5f8-595d-4714-a930-a63f1f997eda.png)
.
