### ISSUE TITLE
trouble with maps mutations drop down

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#96]
after selecting a gene, in the mutations tab, if there are many potential mutations, no suggestions are given in the drop down, if the user types a digit or letter, the drop down is not filtering correctly ie too small of a subet is produced. For example:

select drug PZA
under mutations select gene pncA, in the mutations drop down is says tow many 200something, then look for mutations that contain the digits "13" only one drops down whereas if you then delete the two digits about a dozen drop down? bizarre?

**Comment by doctormo** [comment]
Note: I believe this is the "single entry" bug, where the search feature only shows one item out of those found, no matter what.

**Comment by doctormo** [comment]
Which browser are you using? Testing with Firefox and Chrome don't show this issue at the moment following your steps.

**Comment by mahafarhat** [comment]
I'm using firefox,  another possibly related issue I'm running into is finding mutations, for the following mutation if I type 13, it doesnot show up, but if I type 2289103 it does.
 
SNP_CN_2289103_T139C_T47A_pncA

**Comment by mahafarhat** [comment]
I will close his issue, I haven't had any more trouble like this
